### ISSUE TITLE
nmsutils-plugin disabling on 1.11

### ISSUE THREAD

**Issue by RoboMWM** [sanjay900/NMSUtilsV2#1]
What's happening when run on 1.11 server: https://github.com/sanjay900/NMSUtilsV2/blob/1124e9da78e5964dea13d876d4d27cb17c7cca07/NMSUtils-API/src/main/java/net/tangentmc/nmsUtils/utils/ReflectionManager.java#L20

Not sure what I'm doing wrong... I'm running `mvn package` in NMSUtils-plugin, and getting the shaded version from the target folder...

Is it because there's no source files here? https://github.com/sanjay900/NMSUtilsV2/tree/master/NMSUtils-v1_11_R1

Btw, getting 522 error on your maven repo

**Comment by sanjay900** [comment]
My network at home is down right now, so ill have to get that back up so you can use the maven server.

**Comment by sanjay900** [comment]
Cool, there was a random src/ in the gitignore which was stopping a lot of code from being pushed, thats fixed now.

**Comment by sanjay900** [comment]
Does it work now?

**Comment by RoboMWM** [comment]
Hmm, still doesn't seem so. Not sure if it's because your maven repo is still down. https://gist.github.com/RoboMWM/fa6d620bc347492963fa1aafd8b4d86d

**Comment by sanjay900** [comment]
Yeah, you otherwise would need to build the entire project
It shouldnt build the runner though, so it shouldnt depend on portalstick

**Comment by RoboMWM** [comment]
Ok, seems like it's loading up now. Sorry for the delay, was working on getting GP updated and released.
